baseURL = "/"
languageCode = "en-us"
title = "All Saints Amsterdam"
theme = "dorothy"

# When using ref or relref to resolve page links and a link cannot resolved, it will be logged with this log level.
# Valid values are ERROR (default) or WARNING. Any ERROR will fail the build (exit -1).
# Default value: 'ERROR'

refLinksErrorLevel = 'WARNING'
relrefLinksErrorLevel = 'WARNING'

# URL to be used as a placeholder when a page reference cannot be found in ref or relref. Is used as-is.
refLinksNotFoundURL = "/wiki"

[taxonomies]
  category = 'categories'
  tag = 'tags'
  
[permalinks]
  events = "/:year/:month/:day/:title/"
  page = "/:slug/"
  notes = "/:slug/"
  cookbook = "/:slug/"
[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']